Fixes Issue 161
oss-slu/lrda_website pull request #164
Opened 2024-10-15 01:28 UTC by jwang-101

(WIP) 

REFERENCE:
Fixes #161

CHANGES:
Added a new file to implement the archive function with the notes. The archive function serves almost as a delete function, hiding the user's post from everyone, but on our end we can still see it, for archival purposes. 

REASONING:
This was changed because removed content might be needed later, and we can access it on our end even if the user doesn't think they need it anymore. 

METHODS:
(wip)
Uses the API service to archive the note.

2024-10-15 01:57 UTC, amychen108 requested changes

2024-10-15 01:57 UTC, amychen108 commented on components/ui/archive.tsx
> +export default NoteEditor;
Code looks good but does it function as intended?

2024-10-15 01:57 UTC, amychen108 commented on components/ui/archive.tsx
> +import PropTypes from 'prop-types';
Make sure you import the note page you're using since the delete button is on it.

2024-10-15 16:11 UTC, kate-holdener commented on components/ui/archive.tsx
Looks like @amychen108 tests are for app/lib/components/noteElements/note_editor and @jwang-101 was supposed to build this component. I am not seeing the node_editor component.

2024-10-15 16:12 UTC, kate-holdener commented on components/ui/archive.tsx
> +      const response = await ApiService.archiveNote(note.id);
I don't see archiveNote in ApiService.

2024-10-21 21:13 UTC, BaloneyBoy97 approved these changes
Good Job Justin, your changes passed all test cases! nice work this week!

2024-10-21 23:24 UTC, BaloneyBoy97 approved these changes
Good Job!

2024-10-23 15:44 UTC, kate-holdener requested changes
Please remove commented out code.

2024-10-28 22:32 UTC, amychen108 reviewed
All comments seem good and help explain the code you wrote.
Nice job changing all the deletes into archives instead since we can only archive at the moment.
Functionality is still a work in progress but so far it seems to follow the correct implementation steps you mentioned in your PR.

2024-10-28 22:32 UTC, amychen108 commented on app/lib/components/noteElements/note_handler.ts
> +//
Is this needed or no? Not sure since it's commented out

2024-11-04 22:49 UTC, BaloneyBoy97 approved these changes
great work! all bug fixed! notes are archived correctly!

2024-11-04 23:04 UTC, yashb196 approved these changes

2024-11-04 23:09 UTC, merged